package com.sombrerosoft.ncaa.hibernate;

// Generated Feb 15, 2014 11:57:40 AM by Hibernate Tools 3.4.0.CR1

/**
 * RegularSeasonResults generated by hbm2java
 */
public class RegularSeasonResults implements java.io.Serializable {

	private Integer wscore;
	private Integer lteam;
	private Integer lscore;
	private String wloc;
	private String numot;
	private String season;
	private int daynum;
	private int wteam;
	
	public RegularSeasonResults() {
	}


	public Integer getWscore() {
		return this.wscore;
	}

	public void setWscore(Integer wscore) {
		this.wscore = wscore;
	}

	public Integer getLteam() {
		return this.lteam;
	}

	public void setLteam(Integer lteam) {
		this.lteam = lteam;
	}

	public Integer getLscore() {
		return this.lscore;
	}

	public void setLscore(Integer lscore) {
		this.lscore = lscore;
	}

	public String getWloc() {
		return this.wloc;
	}

	public void setWloc(String wloc) {
		this.wloc = wloc;
	}

	public String getNumot() {
		return this.numot;
	}

	public void setNumot(String numot) {
		this.numot = numot;
	}

	public String getSeason() {
		return season;
	}

	public void setSeason(String season) {
		this.season = season;
	}

	public int getDaynum() {
		return daynum;
	}

	public void setDaynum(int daynum) {
		this.daynum = daynum;
	}

	public int getWteam() {
		return wteam;
	}

	public void setWteam(int wteam) {
		this.wteam = wteam;
	}

}
