package com.sombrerosoft.ncaa.hibernate;

// Generated Feb 15, 2014 11:57:40 AM by Hibernate Tools 3.4.0.CR1

/**
 * SampleSubmission generated by hbm2java
 */
public class SampleSubmission implements java.io.Serializable {

	private String id;
	private Integer pred;

	public SampleSubmission() {
	}

	public SampleSubmission(String id) {
		this.id = id;
	}

	public SampleSubmission(String id, Integer pred) {
		this.id = id;
		this.pred = pred;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Integer getPred() {
		return this.pred;
	}

	public void setPred(Integer pred) {
		this.pred = pred;
	}

}
