package com.sombrerosoft.ncaa.hibernate;

// Generated Feb 15, 2014 11:57:40 AM by Hibernate Tools 3.4.0.CR1

/**
 * Teams generated by hbm2java
 */
public class Teams implements java.io.Serializable {

	private int id;
	private String name;

	public Teams() {
	}

	public Teams(int id) {
		this.id = id;
	}

	public Teams(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
