package com.sombrerosoft.ncaa.hibernate;

// Generated Feb 15, 2014 11:57:40 AM by Hibernate Tools 3.4.0.CR1

/**
 * TourneySlots generated by hbm2java
 */
public class TourneySlots implements java.io.Serializable {

	private String season;
	private String slot;
	private String strongseed;
	private String weakseed;

	public TourneySlots() {
	}

	public String getSeason() {
		return season;
	}

	public void setSeason(String season) {
		this.season = season;
	}

	public String getSlot() {
		return slot;
	}

	public void setSlot(String slot) {
		this.slot = slot;
	}

	public String getStrongseed() {
		return strongseed;
	}

	public void setStrongseed(String strongseed) {
		this.strongseed = strongseed;
	}

	public String getWeakseed() {
		return weakseed;
	}

	public void setWeakseed(String weakseed) {
		this.weakseed = weakseed;
	}



}
