package com.sombrerosoft.ncaa.hibernate;

// Generated Feb 15, 2014 11:57:40 AM by Hibernate Tools 3.4.0.CR1

/**
 * TourneySeeds generated by hbm2java
 */
public class TourneySeeds implements java.io.Serializable {

	private String season;
	private String seed;
	private int team;
	
	public TourneySeeds() {
	}

	public String getSeason() {
		return season;
	}

	public void setSeason(String season) {
		this.season = season;
	}

	public String getSeed() {
		return seed;
	}

	public void setSeed(String seed) {
		this.seed = seed;
	}

	public int getTeam() {
		return team;
	}

	public void setTeam(int team) {
		this.team = team;
	}

}
